### ISSUE TITLE
FE: Create booking component

### ISSUE THREAD

**Issue by OleksandrBrusyltsev** [OleksandrBrusyltsev/Visiting_Grandpa-s_Village#13]
Create Booking component;
Create DatePicker;

![Image](https://github.com/OleksandrBrusyltsev/Visiting_Grandpa-s_Village/assets/124603897/7a2468e9-db0b-412f-a422-4cc7db014c05)

**Comment by OleksandrBrusyltsev** [comment]
1. Добавить анимацию на закрытие модалки. На открытие у меня - получилось, а на закрытые - не могу реализовать, потому что переданный пропс в модалку isOpen - не становится false при закрытии.
2. Исправить баг з навешиванием активного класса на дефолтные даты. Дефолтные даты - это даты которые автоматически установлены в инпутах при открытии календаря. Сегодня - дата заезда, завтра - дата выезда. Они должны иметь активный класс. Но этого почему - то не происходит. Активный класс - навешивается на даты, которые уже потом выбирает пользователь самостоятельно.
3. Нужно придумать решение стилизации активной даты, когда она как бы сливается в активным периодом.
Кто возьмется за это, можем созвонится и я подробно все покажу([telegram](https://t.me/savelieva0509))

![Image](https://github.com/OleksandrBrusyltsev/Visiting_Grandpa-s_Village/assets/124603897/40ea0d19-fb5b-414f-8968-c316316b7a5f)

.

![Image](https://github.com/OleksandrBrusyltsev/Visiting_Grandpa-s_Village/assets/124603897/c94f3752-609c-4bf9-90f0-bd4de1332294)



![Image](https://github.com/OleksandrBrusyltsev/Visiting_Grandpa-s_Village/assets/124603897/8e9585d6-9d5c-4822-bb42-eaa97fe0c906)



![Image](https://github.com/OleksandrBrusyltsev/Visiting_Grandpa-s_Village/assets/124603897/96eb1db0-2fe1-4784-ac1b-20d56fba4677)

**Comment by BerLP2021** [comment]
Added animation, fixed bugs
