### ISSUE TITLE
The cursor type is wrong when hovering it on the word “Зараз” in WelcomeBlock_textWrapper

### ISSUE THREAD

**Issue by Hanna1817** [OleksandrBrusyltsev/Visiting_Grandpa-s_Village#51]
**Steps to reproduce**
1. Enter the https://visiting-grandpa-s-village.vercel.app/uk
2. Navigate to the WelcomeBlock_textWrapper 
3. Hover cursor on the word “Зараз” in WelcomeBlock_textWrapper 
4. Pay attention to the type of cursor

**Actual result**: The cursor type is default when hovering it on the word “Зараз” in WelcomeBlock_textWrapper 

**Expected result:** The cursor type is text when hovering it on the word “Зараз” in WelcomeBlock_textWrapper

**Comment by OleksandrBrusyltsev** [comment]
@Savelieva0509  please check this
