### ISSUE TITLE
The word “Жити” on the uk/houses navigation_item in the Navigation_list on the Houses page is the same font type (regular) with other items in the Navigation_list

### ISSUE THREAD

**Issue by Hanna1817** [OleksandrBrusyltsev/Visiting_Grandpa-s_Village#53]
**Steps to reproduce**
1. Enter the https://visiting-grandpa-s-village.vercel.app/uk
2. Navigate to the Houses page
3. Pay attention to the word “Жити” on the uk/houses navigation_item in the Navigation_list 

**Actual result**: The word “Жити” on the uk/houses navigation_item in the Navigation_list on the Houses page is the same font type (regular) with other items in the Navigation_list

**Expected result:** The word “Жити” on the uk/houses navigation_item in the Navigation_list on the Houses page is Bold according to the design

**Comment by OleksandrBrusyltsev** [comment]
@Hanna1817 I'm just getting to that bug  :)  "Жити" is in our accommodation , maybe we should think about changing it for better readability
