### ISSUE TITLE
fix navigation

### ISSUE THREAD

**Issue by OleksandrBrusyltsev** [OleksandrBrusyltsev/Visiting_Grandpa-s_Village#81]
![Image](https://github.com/user-attachments/assets/53272658-d6d0-4d29-949f-fc1f50617b98) приклад  фігмі 

У нас на сайті https://visiting-grandpa-s-village.vercel.app/uk/houses не виділяється жирним шрифтом відкритий розділ як у фігмі

**Comment by HennadiiBu** [comment]
Походу кто-то уже пофиксил...
![image](https://github.com/user-attachments/assets/9ebf4220-723a-467b-a476-29ba93075832)

**Comment by OleksandrBrusyltsev** [comment]
https://www.figma.com/proto/644WZL1eCYZXtcrqkg2Grt/PROJECT?page-id=0%3A1&node-id=3536-24102&viewport=-7218%2C-686%2C0.09&t=sro0ir90TCoX9YrK-1&scaling=scale-down-width&content-scaling=fixed  check this animation
